export const FETCHING_PRODUCTS = 'FETCHING_PRODUCTS'
export const FAIL_FETCH_PRODUCTS = 'FAIL_FETCH_PRODUCTS'
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS'
export const UPDATE_CART_PRODUCT = 'UPDATE_CART_PRODUCT'
